title = "Max Fierro"
baseURL = 'https://maxfierro.me/'
languageCode = 'en-us'
theme = "hugo-blog-awesome"

# To enable Google Analytics 4 (gtag.js) provide G-MEASUREMENT_ID below.
# To disable  Google Analytics, simply leave the field empty or remove the next line
googleAnalytics = '' # G-MEASUREMENT_ID


# Enable emojis globally
enableEmoji = true

# set markup.highlight.noClasses=false to enable code highlight
[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]] 
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="posts"
    name = 'Posts'
    url = '/posts/'
    weight = 20
  [[menu.main]]
    pageRef="aboutme"
    name = 'About Me'
    url = '/aboutme/'
    weight = 30
  [[menu.main]]
    pageRef="resume"
    name = 'CV'
    url = '/resume/'
    weight = 40

[params]
  sitename = "Blog"
  defaultColor = "light" # set default color mode: dark or light
  description = "Minimal Hugo blog theme with light and dark mode support"

[params.author]
  avatar = "me.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Max Fierro"
  name = "Max F"
  description = "Nice to see you, thank you for stopping by :)"

[[params.socialIcons]]
name = "github"
url = "https://github.com/maxfierrog"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/maxfierro/"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/MaxFierro"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/user/maxfierrog"

[[params.socialIcons]]
name = "email"
url = "mailto:maxfierro@berkeley.edu"

[[params.socialIcons]]
name = "Rss"
url = "index.xml"