baseURL: "https://www.maxfierro.me/"
title: Max Fierro
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: true
buildFuture: true
buildExpired: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

googleAnalytics: G-T3BJYE1E9X

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: Max Fierro
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowAllPagesInArchive: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  math: true

  assets:
    disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Max Fierro"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Hello there
    subtitle: "Welcome, and thank you for stopping by!"
    imageUrl: "https://s.gravatar.com/avatar/326976fc6cd1ab6bc7eb844d43bbcf09?s=300"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Portrait
    buttons:
      - name: About
        url: /about/
      - name: Curriculum Vitae
        url: /about/cv
      - name: Posts
        url: /posts/

  socialIcons:
    - name: instagram
      url: "https://instagram.com/maxfierrog"
    - name: linkedin
      url: "https://linkedin.com/in/maxfierro"
    - name: github
      url: "https://github.com/maxfierrog"
    - name: email
      url: "mailto:maxfierro@berkeley.edu"

  cover:
    hidden: true 
    hiddenInList: true 
    hiddenInSingle: true 

  editPost:
    URL: "https://github.com/maxfierrog/maxfierrog.github.io/tree/main/content"
    Text: "Suggest Changes"
    appendFilePath: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archive
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
